version: '3.8'

services:
  node-backend:
    build:
      context: ./apps/backend-node
      dockerfile: Dockerfile
    container_name: node_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:tallent_password@localhost:5432/tallent_database"

    depends_on:
      - db

  websocket-backend:
    build:
      context: ./apps/websocket-server-ts
      dockerfile: Dockerfile
    container_name: websocket_backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgresql://postgres:tallent_password@localhost:5432/tallent_database"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tallent_password
      POSTGRES_DB: tallent_database
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: